version: '3'

services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
    volumes:
      - ./src/stocks_bot.log:/app/stocks_bot.log
      - ./src/config.json:/app/config.json
    restart: always

